INSERT INTO All_users (
	user_id,
    user_name,
    password,
    roles,
    customer_category,
    phone,
    email_id,
    address1,
    address2,
    city,
    state,
    country,
    zip_code,
    date
) VALUES (
	1,
    'shiv',
    '123456',
    'ROLE_Admin',
    'Gold',
    123456789,
    'shiv@gmail.com',
    'hiyat residence',
    'st church',
    'Lucknow',
    'Up',
    'India',
    12554,
    DATE '2002-05-16'
);




INSERT INTO Carrier (
    BULK_DISCOUNT_BOOKING,
    CARRIERID,
    DISCOUNT_PERCENTAGE_NINTEY_DAYS_ADVANCE_BOOKING,
    DISCOUNT_PERCENTAGE_SIX_DAYS_ADVANCE_BOOKING,
    DISCOUNT_PERCENTAGE_THIRTY_DAYS_ADVANCE_BOOKING,
    GOLD_USER_DISCOUNT,
    PLATINUM_USER_DISCOUNT,
    REFUND_PERCENTAGE_FOR_TICKET_CANCELLATION10DAYS_BEFORE_TRAVEL_DATE,
    REFUND_PERCENTAGE_FOR_TICKET_CANCELLATION20DAYS_BEFORE_TRAVEL_DATE,
    REFUND_PERCENTAGE_FOR_TICKET_CANCELLATION2DAYS_BEFORE_TRAVEL_DATE,
    SILVER_USER_DISCOUNT,
    CARRIER_NAME
) VALUES (
    15,         -- BULK_DISCOUNT_BOOKING
    1,          -- CARRIERID
    30,         -- DISCOUNT_PERCENTAGE_NINTEY_DAYS_ADVANCE_BOOKING
    20,         -- DISCOUNT_PERCENTAGE_SIX_DAYS_ADVANCE_BOOKING
    10,         -- DISCOUNT_PERCENTAGE_THIRTY_DAYS_ADVANCE_BOOKING
    24,         -- GOLD_USER_DISCOUNT
    36,         -- PLATINUM_USER_DISCOUNT
    10,         -- REFUND_PERCENTAGE_FOR_TICKET_CANCELLATION10DAYS_BEFORE_TRAVEL_DATE
    20,         -- REFUND_PERCENTAGE_FOR_TICKET_CANCELLATION20DAYS_BEFORE_TRAVEL_DATE
    4,          -- REFUND_PERCENTAGE_FOR_TICKET_CANCELLATION2DAYS_BEFORE_TRAVEL_DATE
    12,         -- SILVER_USER_DISCOUNT
    'asd'       -- CARRIER_NAME
);




INSERT INTO flight_SCHEDULE(
    BUSINESS_CLASS_BOOKED_DISCOUNT,
    ECONOMY_CLASS_BOOKED_DISCOUNT,
    EXECUTIVE_CLASS_BOOKED_DISCOUNT,
    FLIGHT_ID,
    FLIGHT_SCHEDULE_ID,
    DATE_OF_TRAVEL
) VALUES (
    24,         -- BUSINESS_CLASS_BOOKED_DISCOUNT
    40,         -- ECONOMY_CLASS_BOOKED_DISCOUNT
    12,         -- EXECUTIVE_CLASS_BOOKED_DISCOUNT
    1,          -- FLIGHT_ID
    1,          -- FLIGHT_SCHEDULE_ID (assuming same as flightId, you can change this)
    '2025-12-20' -- DATE_OF_TRAVEL
);



INSERT INTO FLIGHT (
	Flight_ID,
    AIR_FARE,
    CARRIER_ID,
    SEAT_CAPACITY_BUSINESS_CLASS,
    SEAT_CAPACITY_ECONOMY_CLASS,
    SEAT_CAPACITY_EXECUTIVE_CLASS,
    DESTINATION,
    ORIGIN
) VALUES (1,
    2500,
    1,
    20,
    90,
    40,
    'Lucknow',
    'Bangalore'
);


